base_packages:
  - htop
  - atop
  - zstd
base_services:
  - irqbalance
  - systemd-timesyncd
unnecessary_packages:
  - nmap-ncat
  - tcpdump
  - wpa_supplicant
unnecessary_services:
  - atop
  - atopacct
  - chrony
  - rsyslog
  - postfix
journald_config:
  - var: Compress
    val: true
  - var: SystemMaxUse
    val: 1G
  - var: SystemMaxFileSize
    val: 10M
sysctl_config:
  - var: fs.inotify.max_user_watches
    val: 524288
  - var: vm.max_map_count
    val: 1048575
node_timezone: America/New_York
