- name: Download k3s binary
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s"
    checksum: "sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt"
    dest: "artifacts/k3s-binary-{{ k3s_version }}"
    mode: "0755"
  become: false
  delegate_to: localhost
  run_once: true
  when: ansible_facts.architecture == "x86_64"

- name: Download k3s binary
  ansible.builtin.get_url:
    url: "https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/k3s-arm64"
    checksum: "sha256:https://github.com/k3s-io/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt"
    dest: "artifacts/k3s-binary-{{ k3s_version }}"
    mode: "0755"
  become: false
  delegate_to: localhost
  run_once: true
  when: ansible_facts.architecture == "aarch64"

- name: Install k3s binary
  ansible.builtin.copy:
    src: "artifacts/k3s-binary-{{ k3s_version }}"
    dest: "/usr/local/bin/k3s"
    owner: root
    group: root
    mode: "0700"

- name: Create symlinks to k3s
  ansible.builtin.file:
    src: "/usr/local/bin/k3s"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: true
  with_items:
    - kubectl 
    - crictl
    - ctr  
