- name: Deploy common configuration
  hosts: all
  become: true
  roles:
    - common
    - common-user
    - common-mount
  tags:
    - common

- name: Deploy router
  hosts: rpi_router
  become: true
  roles:
    - nat
  tags:
    - router

- name: Deploy dhcpd
  hosts: rpi_dhcp
  become: true
  roles:
    - dhcp
  tags:
    - dhcp

- name: Deploy dns
  hosts: rpi_dns
  become: true
  roles:
    - pihole
  tags:
    - dns

- name: Deploy k3s
  hosts: kube
  become: true
  roles:
    - k3s/binary
    - k3s/prereq
    - k3s/master
  tags:
    - k3s

- name: Deploy samba
  hosts: kube
  become: true
  roles:
    - samba
  tags:
    - samba
