- name: apply o/s configuration
  hosts: all
  become: true
  roles:
    - os-base
    - os-user

- name: configure git servers
  hosts: git
  become: true
  roles:
    - os-firewall
    - git

- name: configure routers
  hosts: routers
  become: true
  roles:
    - rpi
    - router
