- name: install ufw
  ansible.builtin.package:
    name: ufw
    state: present

- name: reset firewall
  community.general.ufw:
    state: reset

- name: deny incoming traffic
  community.general.ufw:
    policy: deny
    direction: incoming

- name: allow outgoing traffic
  community.general.ufw:
    policy: allow
    direction: outgoing

- name: allow ssh
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: enable firewall
  community.general.ufw:
    state: enabled
