apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: pihole
  name: pihole
spec:
  containers:
  - name: pihole
    image: docker.io/pihole/pihole:latest  
    env:
    - name: TZ
      value: America/New_York
    - name: WEBPASSWORD
      value: password
    ports:
    - containerPort: 53
      hostPort: 53
      protocol: TCP
    - containerPort: 53
      hostPort: 53
      protocol: UDP
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    volumeMounts:
    - name: pihole
      mountPath: /etc/pihole:Z
    - name: dnsmasq
      mountPath: /etc/dnsmasq.d:Z
  volumes:
  - name: pihole
    hostPath:
      path: /etc/pihole
      type: Directory
  - name: dnsmasq
    hostPath:
      path: /etc/dnsmasq.d
      type: Directory
