- name: Add admin group
  ansible.builtin.group:
    name: admin
    state: present

- name: Add local user
  ansible.builtin.user:
    name: "{{ base_user }}"
    group: admin
    shell: /bin/bash
    state: present

- name: Add ssh public key for user
  ansible.posix.authorized_key:
    user: "{{ base_user }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present

- name: Add sudoer rule for local user
  ansible.builtin.copy:
    dest: /etc/sudoers.d/admin
    content: "%admin ALL=(ALL:ALL) NOPASSWD:ALL"
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s

- name: Configure bash aliases
  ansible.builtin.blockinfile:
    path: "/home/{{ base_user }}/.bashrc"
    block: |
      export LS_OPTIONS='--color=auto'
      eval "`dircolors`"
      alias ls='ls $LS_OPTIONS'
      alias l='ls -CF'
      alias la='ls -AF'
      alias ll='ls -alF'

- name: Remove unwanted users
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
  with_items: "{{ unwanted_users }}"
  failed_when: false

- name: Disable root account
  ansible.builtin.user:
    name: root
    password_lock: yes
