- name: Install git packages
  ansible.builtin.package:
    name: git
    state: present

- name: Add git user
  ansible.builtin.user:
    name: "{{ git_user }}"
    shell: /bin/bash
    state: present

- name: Add ssh public key for git user
  ansible.posix.authorized_key:
    user: "{{ git_user }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present
