- name: install git packages
  ansible.builtin.package:
    name: git
    state: present

- name: add local user
  ansible.builtin.user:
    name: "{{ git_user }}"
    shell: /bin/bash
    state: present

- name: add ssh public key for user
  ansible.posix.authorized_key:
    user: "{{ git_user }}"
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    state: present
