- name: remove rpi undesirable packages
  ansible.builtin.package:
    name: "{{ rpi_unnecessary_packages }}"
    state: absent

- name: disable rpi unnecessary services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items: "{{ rpi_unnecessary_services }}"
  failed_when: false
