- name: restart firewalld
  service:
    name: firewalld
    state: restarted
- name: restart isc-dhcp-server
  service:
    name: isc-dhcp-server
    state: restarted
- name: restart networking
  service:
    name: networking
    state: restarted
