- name: restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
- name: restart isc-dhcp-server
  ansible.builtin.service:
    name: isc-dhcp-server
    state: restarted
- name: restart networking
  ansible.builtin.service:
    name: networking
    state: restarted
