# package configuration

- name: update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
  register: upgrade

- name: install base packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages }}"

- name: install base services
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_services }}"

- name: remove undesirable packages
  ansible.builtin.package:
    name: "{{ unnecessary_packages }}"
    state: absent

- name: disable unnecessary services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items: "{{ unnecessary_services }}"
  failed_when: false

# host configuration

- name: set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"

- name: add FQDN to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    state: present

- name: set timezone
  community.general.timezone:
    name: "{{ node_timezone }}"

# service configuration

- name: configure ssh
  ansible.builtin.copy:
    src: etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: reload ssh

- name: configure journald
  ansible.builtin.lineinfile:
    dest: /etc/systemd/journald.conf
    line: '{{ item.var }}={{ item.val }}'
    insertafter: '\[Journal\]'
    state: present
  with_items: "{{ journald_config | default([]) }}"
  notify: restart journald

- name: tune system
  ansible.posix.sysctl:
    name: "{{ item.var }}"
    value: "{{ item.val }}"
    state: present
    sysctl_file: /etc/sysctl.d/00-ansible.conf
    reload: true
  with_items: "{{ sysctl_config }}"
  tags: sysctl

- name: enable timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: started
    enabled: true
