- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname_short }}"

- name: Add FQDN to /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    state: present
