- name: Update kernel
  ansible.builtin.package:
    name: "{{ kernel_packages }}"
    state: latest
  register: kernel_update

- name: Update initramfs
  ansible.builtin.command: update-grub
  when:
    - kernel_update.changed
    - ansible_os_family == "Debian"

- name: Restart nodes
  ansible.builtin.command: reboot
  async: 1
  poll: 0
  when: kernel_update.changed

- name: Wait for system to become reachable
  ansible.builtin.wait_for_connection:
    delay: 1
    timeout: 300
  when: kernel_update.changed
