- name: Tune system
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/10-tuning.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items:
    - { name: net.core.bpf_jit_harden, value: 2 }
    - { name: net.core.default_qdisc, value: fq }
    - { name: net.core.dev_weight, value: 64 }
    - { name: net.core.netdev_max_backlog, value: 16384 }
    - { name: net.core.optmem_max, value: 65535 }
    - { name: net.core.rmem_default, value: 262144 }
    - { name: net.core.rmem_max, value: 16777216 }
    - { name: net.core.somaxconn, value: 32768 }
    - { name: net.core.wmem_default, value: 262144 }
    - { name: net.core.wmem_max, value: 16777216 }
    - { name: net.ipv4.ip_local_port_range, value: 2000 64999 }
    - { name: net.ipv4.neigh.default.gc_interval, value: 30 }
    - { name: net.ipv4.neigh.default.gc_thresh1, value: 32 }
    - { name: net.ipv4.neigh.default.gc_thresh2, value: 1024 }
    - { name: net.ipv4.neigh.default.gc_thresh3, value: 2048 }
    - { name: net.ipv4.neigh.default.proxy_qlen, value: 96 }
    - { name: net.ipv4.neigh.default.unres_qlen, value: 6 }
    - { name: net.ipv4.tcp_ecn, value: 1 }
    - { name: net.ipv4.tcp_fastopen, value: 3 }
    - { name: net.ipv4.tcp_fin_timeout, value: 15 }
    - { name: net.ipv4.tcp_keepalive_intvl, value: 15 }
    - { name: net.ipv4.tcp_keepalive_probes, value: 5 }
    - { name: net.ipv4.tcp_keepalive_time, value: 1800 }
    - { name: net.ipv4.tcp_max_orphans, value: 16384 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 2048 }
    - { name: net.ipv4.tcp_max_tw_buckets, value: 1440000 }
    - { name: net.ipv4.tcp_moderate_rcvbuf, value: 1 }
    - { name: net.ipv4.tcp_no_metrics_save, value: 1 }
    - { name: net.ipv4.tcp_orphan_retries, value: 0 }
    - { name: net.ipv4.tcp_reordering, value: 3 }
    - { name: net.ipv4.tcp_retries1, value: 3 }
    - { name: net.ipv4.tcp_retries2, value: 15 }
    - { name: net.ipv4.tcp_rfc1337, value: 1 }
    - { name: net.ipv4.tcp_rmem, value: 8192 87380 16777216 }
    - { name: net.ipv4.tcp_sack, value: 0 }
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
    - { name: net.ipv4.tcp_syn_retries, value: 5 }
    - { name: net.ipv4.tcp_synack_retries, value: 5 }
    - { name: net.ipv4.tcp_syncookies, value: 1 }
    - { name: net.ipv4.tcp_timestamps, value: 1 }
    - { name: net.ipv4.tcp_tw_reuse, value: 1 }
    - { name: net.ipv4.tcp_wmem, value: 8192 65536 16777216 }
    - { name: net.ipv4.udp_rmem_min, value: 16384 }
    - { name: net.ipv4.udp_wmem_min, value: 16384 }
