- name: Tune system
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/10-tuning.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  with_items: "{{ sysctl_config }}"
