# firewalld setup

- name: install router services
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ router_services }}"

- name: assign home zone to lan interface
  ansible.posix.firewalld:
    zone: home
    interface: "{{ router_intf_lan }}"
    permanent: true
    state: enabled
  notify:
    - restart firewalld

- name: assign public zone to wan interface
  ansible.posix.firewalld:
    zone: public
    interface: "{{ router_intf_wan }}"
    permanent: true
    state: enabled
  notify:
    - restart firewalld

- name: enable masquerade on public zone
  ansible.posix.firewalld:
    zone: public
    masquerade: true
    permanent: true
    state: enabled
  notify:
    - restart firewalld

- name: permit traffic in home zone for dns service
  ansible.posix.firewalld:
    zone: home
    service: dns
    permanent: true
    state: enabled
  notify:
    - restart firewalld

- name: permit traffic in home zone for dhcp service
  ansible.posix.firewalld:
    zone: home
    service: dhcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld

# isc-dhcp-server setup

- name: disable dhcpcd
  ansible.builtin.service:
    name: dhcpcd
    state: stopped
    enabled: false

- name: configure isc-dhcp-server default
  ansible.builtin.template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: '0644'
  notify: reload isc-dhcp-server

- name: configure isc-dhcp-server
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart isc-dhcp-server

- name: enable isc-dhcp-server
  ansible.builtin.service:
    name: isc-dhcp-server
    state: started
    enabled: true
