- name: Create k3s directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  with_items:
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s

- name: Install k3s binary
  ansible.builtin.copy:
    src: "artifacts/k3s-binary-{{ k3s_version }}"
    dest: "/usr/local/bin/k3s"
    owner: root
    group: root
    mode: "0700"
  register: k3s_binary

- name: Create k3s agent service file
  ansible.builtin.template:
    src: k3s-agent.service.j2
    dest: /etc/systemd/system/k3s-agent.service
    owner: root
    group: root
    mode: "0400"
  register: k3s_agent_service

- name: Stop k3s agent service
  ansible.builtin.systemd:
    name: k3s-agent
    state: stopped
  when: k3s_binary.changed or k3s_agent_service.changed

- name: Start k3s agent service
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    daemon_reload: true
    enabled: true

- name: Create symlinks to k3s
  ansible.builtin.file:
    src: "/usr/local/bin/k3s"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    force: true
  with_items:
    - kubectl 
  